//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PinkCard2.rc
//
#define IDR_MANIFEST                    1
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PINKCARD2_DIALOG            102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_ADDGROUP_DIALOG             104
#define IDD_SCHEDULE_SEND_DLG           105
#define IDD_SEND_MESSAGE_DLG            106
#define IDD_FUNGFXMESSAGEBOXDLG         107
#define IDD_FUNGFXASKMESSAGEBOXDLG      108
#define IDD_ADDSCHEDULEEVENT_DLG        109
#define IDB_BROKEN_PC_BITMAP            129
#define IDB_OK_PC_BITMAP                131
#define ID_Menu                         135
#define IDD_DIALOG_OPTIONS              136
#define IDD_DIALOG_GROUPMANAGER         137
#define IDB_BITMAP_SPLASH               139
#define ID_PINKCARD2_SHOW               142
#define IDR_TRAY_MENU1                  144
#define ID_TRAYMENU_SHOW1               145
#define ID_TRAYMENU_CLOSE1              146
#define IDB_PEOPLE_BITMAP               152
#define IDR_MAINDLG_MENU1               156
#define ID_FILE_OPEN158                 158
#define ID_FILE_EDIT                    159
#define IDR_CONTEXT_HOSTS_MENU1         160
#define ID_SENDMESSAGE_SENDMESSAGE      161
#define ID_SENDMESSAGE_SENDFILES        162
#define ID_SENDMESSAGE_SENDIMAGES       163
#define ID_MENU_SCHEDULESEND            164
#define ID_MENU_SCHEDULESEND165         165
#define IDR_CONTEXT_GROUP_MENU1         166
#define ID_GROUPCONTEXTMENU_SENDMESSAGES 167
#define ID_GROUPCONTEXTMENU_SENDFILES   168
#define ID_GROUPCONTEXTMENU_SENDIMAGES  169
#define ID_GROUPCONTEXTMENU_SCHEDULESEND 170
#define IDR_MAINFRAME                   174
#define ID_PINKCARD2MENU_ABOUT          175
#define IDB_BITMAP_ABOUT                181
#define IDC_LAN_RESOURCESLIST1          1001
#define IDC_GROUPS_LIST1                1003
#define IDC_BUTTON_EXIT                 1008
#define IDC_BUTTON_OPTIONS              1013
#define IDC_BUTTON_GROUPS_EDIT          1014
#define IDC_LIST_GROUPEDIT_LANRESOURCES 1019
#define IDC_LIST_GROUPEDIT_GROUPDETAILS 1020
#define IDC_COMBO_LANDOMAIN             1021
#define IDC_OPTIONS_STATIC1             1022
#define IDC_OPTIONS_PROVNAME_EDIT1      1023
#define IDC_OPTIONS_STATIC2             1024
#define IDC_OPTIONS_PORT_EDIT2          1025
#define IDC_BUTTON_ABOUT                1026
#define IDC_ADDGRP_BUTTON_OK            1026
#define IDC_BUTTON_GROUPS_ADD           1027
#define IDC_BUTTON_GROUPS_DELETE        1028
#define IDC_ADDGRP_BUTTON_CLOSE         1029
#define IDC_ADDGRP_EDIT_INPUT1          1030
#define IDC_ADDGRP_STATIC1              1031
#define IDC_OPTIONS_CHECK_SPLASH        1032
#define IDC_OPTIONS_SYSPATH_EDIT        1033
#define IDC_OPTIONS_STATIC3             1034
#define IDC_OPTIONS_DEFAULT_BUTTON      1035
#define IDC_SCHEDULE_SEND_BUTTON_OK     1036
#define IDC_SCHEDULE_SEND_BUTTON_CANCEL 1037
#define IDC_SCHEDULE_SEND_MONTHCALENDAR1 1039
#define IDC_SCHEDULE_SEND_EVENT_LIST1   1040
#define IDC_SCHEDULE_SEND_TIMEPICKER    1041
#define IDC_SCHEDULESENDDLG_TIME        1041
#define IDC_SEND_MESSAGEDLG_RICHEDIT21  1042
#define IDC_BUTTON1                     1043
#define IDC_SEND_MESSAGEDLG_BUTTON_CANCEL 1044
#define IDC_LIST_GROUP_OK_BUTTON        1045
#define IDC_LIST_GROUP_CANCEL_BUTTON    1046
#define IDC_LIST_GROUP_ADDTOGRP_BUTTON  1047
#define IDC_LIST_GROUP_DEL_BUTTON       1048
#define IDC_GROUPEDITOR_STATIC1         1049
#define IDC_FUNMSGDLG_OK_BUTTON1        1050
#define IDC_OPTIONS_CHECK_AUTOHIDEONSEND_CHECK 1051
#define IDC_OPTIONS_SKINPATH_EDIT       1052
#define IDC_OPTIONS_SETSKINFOLDER_BUTTON 1053
#define IDC_OPTIONS_CHECK_GFX_CHECK     1054
#define IDC_OPTIONS_SETPATHFOLDER_BUTTON 1055
#define IDC_OPTIONS_DEFAULTSKINPATH_BUTTON 1056
#define IDC_FUNASKMBOX_BUTTON_NO        1057
#define IDC_FUNASKMBOX_BUTTON_YES       1058
#define IDC_BUTTON_TEST                 1059
#define IDC_DATETIMEPICKER2             1062
#define IDC_SCHEDULESENDDLG_DATE        1062
#define IDC_SCHEDULE_S_BUTTON_ADD       1063
#define IDC_SCHEDULE_S_BUTTON_DEL       1064
#define IDC_ADDSCHEDULE_BUTTON_OK       1065
#define IDC_ADDSCHEDULE_BUTTON_CANCEL   1066
#define IDC_SCHEDULEEVENT_EDIT_COMMENT  1067

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        182
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
